-- Generated from generator/demo_specs/aws-philippines-bpo-contact-center.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-philippines-bpo-contact-center
-- This is the schema that is actually deployed for PH_BPO_CONTACT_CENTER.

-- Alerts fire on the bottom tail of Avg Handle Time
-- (lower is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.09) WITHIN GROUP (ORDER BY KPI_AVG_HANDLE_TIME) AS T
  FROM RAW.INTERACTIONS
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_AVG_HANDLE_TIME <= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_AVG_HANDLE_TIME), 2) AS AVG_HANDLE_TIME,
  ROUND(AVG(f.KPI_CSAT_SCORE), 2) AS AVG_CSAT_SCORE,
  ROUND(AVG(f.KPI_FIRST_CALL_RESOLUTION), 2) AS AVG_FIRST_CALL_RESOLUTION,
  ROUND(AVG(f.KPI_OCCUPANCY_RATE), 2) AS AVG_OCCUPANCY_RATE,
  ROUND(AVG(f.KPI_AGENT_ATTRITION), 2) AS AVG_AGENT_ATTRITION
FROM RAW.INTERACTIONS f
JOIN RAW.ACCOUNTS e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_AVG_HANDLE_TIME), 2) AS AVG_HANDLE_TIME,
  ROUND(AVG(f.KPI_CSAT_SCORE), 2) AS AVG_CSAT_SCORE,
  ROUND(AVG(f.KPI_FIRST_CALL_RESOLUTION), 2) AS AVG_FIRST_CALL_RESOLUTION,
  ROUND(AVG(f.KPI_OCCUPANCY_RATE), 2) AS AVG_OCCUPANCY_RATE,
  ROUND(AVG(f.KPI_AGENT_ATTRITION), 2) AS AVG_AGENT_ATTRITION
FROM RAW.INTERACTIONS f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_AVG_HANDLE_TIME) AS KPI_AVG_HANDLE_TIME, AVG(KPI_CSAT_SCORE) AS KPI_CSAT_SCORE, AVG(KPI_FIRST_CALL_RESOLUTION) AS KPI_FIRST_CALL_RESOLUTION, AVG(KPI_OCCUPANCY_RATE) AS KPI_OCCUPANCY_RATE, AVG(KPI_AGENT_ATTRITION) AS KPI_AGENT_ATTRITION FROM RAW.INTERACTIONS),
     en AS (SELECT SUM(KPI_CALLS_HANDLED_MTD) AS KPI_CALLS_HANDLED_MTD, SUM(KPI_AGENTS_ACTIVE) AS KPI_AGENTS_ACTIVE FROM RAW.ACCOUNTS)
  SELECT 1 AS SORT_ORDER, 'Calls Handled (MTD)' AS TITLE, KPI_CALLS_HANDLED_MTD AS VALUE_NUM, TO_VARCHAR(CAST(ROUND(((KPI_CALLS_HANDLED_MTD) / 1000000), 1) AS DECIMAL(38,1))) || 'M' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'Avg Handle Time' AS TITLE, KPI_AVG_HANDLE_TIME AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_AVG_HANDLE_TIME)) AS DECIMAL(38,0))) || ':32' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'CSAT Score' AS TITLE, KPI_CSAT_SCORE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_CSAT_SCORE), 1) AS DECIMAL(38,1))) || '/5' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Agents Active' AS TITLE, KPI_AGENTS_ACTIVE AS VALUE_NUM, LTRIM(TO_VARCHAR(CAST(ROUND((KPI_AGENTS_ACTIVE)) AS DECIMAL(38,0)), '999,999,999,999')) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'First Call Resolution' AS TITLE, KPI_FIRST_CALL_RESOLUTION AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_FIRST_CALL_RESOLUTION)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'Occupancy Rate' AS TITLE, KPI_OCCUPANCY_RATE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_OCCUPANCY_RATE)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 7 AS SORT_ORDER, 'Agent Attrition' AS TITLE, KPI_AGENT_ATTRITION AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_AGENT_ATTRITION), 1) AS DECIMAL(38,1))) || '%/mo' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
