-- ============================================================================
-- 06_ML_MODELS.SQL — ML Functions for Contact Center Intelligence & CSAT Optimization
-- ============================================================================
USE DATABASE CONTACT_CENTER_AI;
USE SCHEMA ML;

-- ML.CLASSIFICATION: CSAT_PREDICTOR
CREATE OR REPLACE SNOWFLAKE.ML.CLASSIFICATION ML.CSAT_PREDICTOR(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.INTERACTION_ENRICHED'),
  TARGET_COLNAME => 'CSAT_CATEGORY'
);

-- ML.FORECAST: CSAT_TREND_MODEL
CREATE OR REPLACE SNOWFLAKE.ML.FORECAST ML.CSAT_TREND_MODEL(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.ACCOUNT_HEALTH_SCORE'),
  SERIES_COLNAME => 'ACCOUNT_ID',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'CSAT_SCORE'
  
);

CREATE OR REPLACE TABLE ML.CSAT_TREND_MODEL_RESULTS AS
SELECT * FROM TABLE(ML.CSAT_TREND_MODEL!FORECAST(FORECASTING_PERIODS => 14));

