-- ============================================================================
-- 99_RESET.SQL — Reset Contact Center Intelligence & CSAT Optimization to clean demo state
-- ============================================================================
USE DATABASE CONTACT_CENTER_AI;

-- Suspend tasks during demo
ALTER TASK IF EXISTS APP.TASK_ENRICH_INTERACTIONS SUSPEND;
ALTER TASK IF EXISTS APP.TASK_UPDATE_HEALTH_SCORES SUSPEND;
ALTER TASK IF EXISTS APP.TASK_GENERATE_COACHING SUSPEND;

-- Force refresh Dynamic Tables
ALTER DYNAMIC TABLE CURATED.ACCOUNT_HEALTH_SCORE REFRESH;
ALTER DYNAMIC TABLE CURATED.AGENT_SENTIMENT_SCORES REFRESH;
ALTER DYNAMIC TABLE CURATED.INTERACTION_ENRICHED REFRESH;
ALTER DYNAMIC TABLE CURATED.COMPLAINT_PARETO REFRESH;

-- Verify key demo numbers
-- SELECT COUNT(*) FROM CONTACT_CENTER_AI.RAW.INTERACTIONS → 620000
-- SELECT COUNT(*) FROM CONTACT_CENTER_AI.RAW.TRANSCRIPTS → 450000
-- SELECT COUNT(DISTINCT ACCOUNT_ID) FROM CONTACT_CENTER_AI.CURATED.ACCOUNT_HEALTH_SCORE WHERE CSAT_STATUS = 'BELOW_SLA' → 5

-- Resume tasks
ALTER TASK IF EXISTS APP.TASK_GENERATE_COACHING RESUME;
ALTER TASK IF EXISTS APP.TASK_UPDATE_HEALTH_SCORES RESUME;
ALTER TASK IF EXISTS APP.TASK_ENRICH_INTERACTIONS RESUME;
